# Generated by Django 4.1.7 on 2023-06-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default='', max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
