# Generated by Django 4.1.7 on 2023-06-29 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
