# Generated by Django 4.1.7 on 2023-06-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='time_created',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
