# Generated by Django 4.2.2 on 2023-06-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_myimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImage',
        ),
    ]
