# Generated by Django 4.1.7 on 2023-06-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='untitled', max_length=50),
        ),
    ]
